bloccit/config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :posts

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

bloccit/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

bloccit/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  default_scope { order('updated_at DESC') }

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
    FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

bloccit/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

bloccit/app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings

  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic

  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?
    label_string.split(",").map do |label|
    Label.find_or_create_by(name: label.strip)
     end
   end

end

bloccit/app/models/labeling.rb
class Labeling < ActiveRecord::Base

   belongs_to :labelable, polymorphic: true
   belongs_to :label
end

bloccit/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end
  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end
  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end


end

bloccit/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

bloccit/app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable

  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : where(public: true) }
end

bloccit/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }

  before_create :generate_auth_token

     EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


     validates :name, length: { minimum: 1, maximum: 100 }, presence: true

    validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
    validates :password, length: { minimum: 6 }, allow_blank: true

     validates :email,
               presence: true,
               uniqueness: { case_sensitive: false },
               length: { minimum: 3, maximum: 100 },
               format: { with: EMAIL_REGEX }


     has_secure_password

    enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end
  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
      loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
      end
  end

end

bloccit/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end

end

bloccit/app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)

    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
      else
       content_tag :div, capture(&block), class: 'form-group'
     end
    end
end

bloccit/app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

bloccit/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bloccit/app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

bloccit/app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

bloccit/app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end
  def destroy_session(user)
    session[:user_id] = nil
  end
  def current_user
    User.find_by(id: session[:user_id])
  end
end

bloccit/app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
        current_user && current_user.admin?
   end
end

bloccit/app/helpers/users_helper.rb
module UsersHelper
end

bloccit/app/helpers/votes_helper.rb
module VotesHelper
end

bloccit/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bloccit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Bloccit", root_path %></li>
    <li><%= link_to "Topics", topics_path %></li>
    <li><%= link_to "About", about_path %></li>

    <div class="pull-right user-info">

      <% if current_user %>
      <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
       <div class="pull-right">

         <%= link_to current_user.name, user_path(current_user) %> <br/> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
       </div>



         </div>
  </ul>
<div class="flash">
 <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
        </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
     </div>
 <%= yield %>
</div>

</body>
</html>
<% end %>